# Generated by Django 3.0.8 on 2020-08-03 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=30, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=30, verbose_name='dir')),
                ('telefono', models.CharField(max_length=30, verbose_name='tel')),
                ('celular', models.CharField(max_length=30, verbose_name='cel')),
                ('email', models.EmailField(max_length=30, verbose_name='correo')),
            ],
        ),
    ]
