# Generated by Django 3.0.8 on 2020-08-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_juegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamos', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=30, verbose_name='NombreCl')),
                ('idCliente', models.IntegerField(verbose_name='idC')),
                ('nombreJuego', models.CharField(max_length=30, verbose_name='NombreJ')),
                ('fechaPrestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fechap')),
                ('fechaVence', models.DateField(verbose_name='fechaV')),
                ('Correo', models.CharField(max_length=30, verbose_name='correoP')),
            ],
        ),
    ]
